image: alpine
stages:
  - build
  - deploy
build:
  image: aergus/latex
  stage: build
  script:
    - latexmk -xelatex -pdf ${FILE_NAME}.tex
  artifacts:
    paths:
      - ${FILE_NAME}.pdf
  only:
    - master
    - dev
pages:
  stage: deploy
  script:
    - mkdir public
    - cp ${FILE_NAME}.pdf public
  artifacts:
    paths:
      - public
  only:
    - master
