image: alpine
stages:
  - build
  - deploy
build:
  image: aergus/latex
  stage: build
  script:
    - cd english_cv
    - latexmk -pdf cv.tex
    - cd ../farsi_resume1
    - latexmk -pdf farsi_resume1.tex
    - cd ..
  artifacts:
    paths:
      - ./english_cv/cv.pdf
      - ./farsi_resume1/farsi_resume1.pdf
  only:
    - master
    - dev
pages:
  stage: deploy
  script:
    - mkdir public
    - cp ./english_cv/cv.pdf public
    - cp ./farsi_resume1/farsi_resume1.pdf public
  artifacts:
    paths:
      - public
  only:
    - master
