image: alpine
stages:
  - build
  - deploy
build:
  image: aergus/latex
  stage: build
  script:
    - bash build.sh
  artifacts:
    paths:
      - ./english_cv/english_cv.pdf
      - ./farsi_resume/farsi_resume.pdf
  only:
    - master
    - dev
pages:
  stage: deploy
  script:
    - mkdir public
    - cp ./english_cv/english_cv.pdf public
    - cp ./farsi_resume/farsi_resume.pdf public
  artifacts:
    paths:
      - public
  only:
    - master
