sudo: required
language: generic
services: docker

script:
  - mkdir public
  - docker run --rm -v $(pwd)/english_cv:/tex aergus/latex /bin/sh -c "cd /tex; latexmk -pdf english_cv.tex"
  - docker run --rm -v $(pwd)/farsi_resume:/tex aergus/latex /bin/sh -c "cd /tex; latexmk -pdf farsi_resume.tex"
  - cp english_cv/english_cv.pdf public
  - cp farsi_resume/farsi_resume.pdf public

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
