sudo: required
language: generic
services: docker

script:
  - bash build.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
